apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomstringgen-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomstringgen
  template:
    metadata:
      labels:
        app: randomstringgen
    spec:
      containers:
        - name: randomstringgen
          image: anmoltuni/logoutput:v1.07
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "8888"
