apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
      - name: shared-info
        emptyDir: {}
      containers:
      - name: timestamp
        image: anmoltuni/timestamp:v1.10
        volumeMounts:
        - name: shared-info
          mountPath: /usr/src/app/shared/
      - name: hashgen
        image: anmoltuni/hashgen:v1.10
        volumeMounts:
        - name: shared-info
          mountPath: /usr/src/app/shared/