apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudapp
  template:
    metadata:
      labels:
        app: crudapp
    spec:
      volumes: 
      - name: image-pv
        persistentVolumeClaim:
          claimName: image-claim
      containers:
        - name: todo-frontend
          image: anmoltuni/crudapp:v2.02.1
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "9999"
          ports:
          - containerPort: 9999
          volumeMounts:
          - name: image-pv
            mountPath: /tmp/image_cache/
        - name: todo-backend
          image: anmoltuni/todo-backend:v2.02
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3000"
          ports:
          - containerPort: 3000